language: elixir
elixir:
    - 1.6
    - 1.7
    - 1.8
otp_release:
    - 19.3
    - 20.3
    - 21.0

addons:
    postgresql: '9.6.1'

services:
    - postgresql

before_script:
    - mix deps.get
    - mix do ecto.create, ecto.migrate
    - nvm install 6.2 && nvm use 6.2

script:
    - mix test
    - mix credo
    - cd assets && npm install

cache:
    directories:
        - assets/node_modules
