language: elixir

elixir:
    - 1.6

addons:
    postgresql: '9.6.1'

services:
    - postgresql

before_script:
    - mix deps.get
    - mix do ecto.create, ecto.migrate

script:
    - mix test
    - mix credo
